/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RateBreakdown = IDL.Record({
  'serviceFees' : IDL.Nat,
  'taxes' : IDL.Nat,
  'baseFare' : IDL.Nat,
});
export const TransportType = IDL.Variant({
  'bus' : IDL.Null,
  'train' : IDL.Null,
  'taxi' : IDL.Null,
});
export const Time = IDL.Int;
export const Route = IDL.Record({
  'id' : IDL.Text,
  'destination' : IDL.Text,
  'rateBreakdown' : RateBreakdown,
  'origin' : IDL.Text,
  'operatorName' : IDL.Text,
  'routeName' : IDL.Text,
  'distanceKm' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'transportType' : TransportType,
  'schedule' : IDL.Vec(Time),
  'priceCents' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'costInStripeCents' : IDL.Nat,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'bookingTime' : Time,
  'route' : Route,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'bookingId' : IDL.Text,
  'user' : IDL.Principal,
  'reviewText' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
  'addRoute' : IDL.Func([Route], [], []),
  'addRouteWithRateBreakdown' : IDL.Func(
      [
        TransportType,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(Time),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([Booking], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteRoute' : IDL.Func([IDL.Text], [], []),
  'getAllRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'getAllRoutesForType' : IDL.Func(
      [TransportType],
      [IDL.Vec(Route)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReviewsForRoute' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getRoutesWithAvailableSchedule' : IDL.Func(
      [Time],
      [IDL.Vec(Route)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listRoutesByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Route)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchRoutesByOperator' : IDL.Func([IDL.Text], [IDL.Vec(Route)], ['query']),
  'searchRoutesByOperatorAndType' : IDL.Func(
      [IDL.Text, TransportType],
      [IDL.Vec(Route)],
      ['query'],
    ),
  'searchRoutesByTimeRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Route)],
      ['query'],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBooking' : IDL.Func([Booking], [], []),
  'updateRoute' : IDL.Func([Route], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RateBreakdown = IDL.Record({
    'serviceFees' : IDL.Nat,
    'taxes' : IDL.Nat,
    'baseFare' : IDL.Nat,
  });
  const TransportType = IDL.Variant({
    'bus' : IDL.Null,
    'train' : IDL.Null,
    'taxi' : IDL.Null,
  });
  const Time = IDL.Int;
  const Route = IDL.Record({
    'id' : IDL.Text,
    'destination' : IDL.Text,
    'rateBreakdown' : RateBreakdown,
    'origin' : IDL.Text,
    'operatorName' : IDL.Text,
    'routeName' : IDL.Text,
    'distanceKm' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'transportType' : TransportType,
    'schedule' : IDL.Vec(Time),
    'priceCents' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'costInStripeCents' : IDL.Nat,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'completed' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'bookingTime' : Time,
    'route' : Route,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'bookingId' : IDL.Text,
    'user' : IDL.Principal,
    'reviewText' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
    'addRoute' : IDL.Func([Route], [], []),
    'addRouteWithRateBreakdown' : IDL.Func(
        [
          TransportType,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(Time),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([Booking], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteRoute' : IDL.Func([IDL.Text], [], []),
    'getAllRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'getAllRoutesForType' : IDL.Func(
        [TransportType],
        [IDL.Vec(Route)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReviewsForRoute' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getRoutesWithAvailableSchedule' : IDL.Func(
        [Time],
        [IDL.Vec(Route)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listRoutesByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Route)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchRoutesByOperator' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Route)],
        ['query'],
      ),
    'searchRoutesByOperatorAndType' : IDL.Func(
        [IDL.Text, TransportType],
        [IDL.Vec(Route)],
        ['query'],
      ),
    'searchRoutesByTimeRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Route)],
        ['query'],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBooking' : IDL.Func([Booking], [], []),
    'updateRoute' : IDL.Func([Route], [], []),
  });
};

export const init = ({ IDL }) => { return []; };